/* Generated By:JavaCC: Do not edit this line. Parser0Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser0Constants {
	
	/**
	 * End of File.
	 */
	int EOF = 0;
	/**
	 * RegularExpression Id.
	 */
	int DEREF = 5;
	/**
	 * RegularExpression Id.
	 */
	int MUT = 6;
	/**
	 * RegularExpression Id.
	 */
	int NEW = 7;
	/**
	 * RegularExpression Id.
	 */
	int IF = 8;
	/**
	 * RegularExpression Id.
	 */
	int ELSE = 9;
	/**
	 * RegularExpression Id.
	 */
	int WHILE = 10;
	/**
	 * RegularExpression Id.
	 */
	int PRINTLN = 11;
	/**
	 * RegularExpression Id.
	 */
	int TRUE = 12;
	/**
	 * RegularExpression Id.
	 */
	int FALSE = 13;
	/**
	 * RegularExpression Id.
	 */
	int NOT = 14;
	/**
	 * RegularExpression Id.
	 */
	int EQ = 15;
	/**
	 * RegularExpression Id.
	 */
	int GR = 16;
	/**
	 * RegularExpression Id.
	 */
	int GREQ = 17;
	/**
	 * RegularExpression Id.
	 */
	int AND = 18;
	/**
	 * RegularExpression Id.
	 */
	int OR = 19;
	/**
	 * RegularExpression Id.
	 */
	int LET = 20;
	/**
	 * RegularExpression Id.
	 */
	int ID = 21;
	/**
	 * RegularExpression Id.
	 */
	int NUM = 22;
	/**
	 * RegularExpression Id.
	 */
	int PLUS = 23;
	/**
	 * RegularExpression Id.
	 */
	int MINUS = 24;
	/**
	 * RegularExpression Id.
	 */
	int MULT = 25;
	/**
	 * RegularExpression Id.
	 */
	int DIV = 26;
	/**
	 * RegularExpression Id.
	 */
	int LPAR = 27;
	/**
	 * RegularExpression Id.
	 */
	int RPAR = 28;
	/**
	 * RegularExpression Id.
	 */
	int BIND = 29;
	/**
	 * RegularExpression Id.
	 */
	int SEMI = 30;
	/**
	 * RegularExpression Id.
	 */
	int DSEMI = 31;
	/**
	 * RegularExpression Id.
	 */
	int LCBRA = 32;
	/**
	 * RegularExpression Id.
	 */
	int RCBRA = 33;
	
	/**
	 * Lexical state.
	 */
	int DEFAULT = 0;
	
	/**
	 * Literal token values.
	 */
	String[] tokenImage = {
			"<EOF>",
			"\" \"",
			"\"\\t\"",
			"\"\\r\"",
			"\"\\n\"",
			"\"~\"",
			"\"mut\"",
			"\"new\"",
			"\"if\"",
			"\"else\"",
			"\"while\"",
			"\"println\"",
			"\"true\"",
			"\"false\"",
			"\"!\"",
			"\"==\"",
			"\">\"",
			"\">=\"",
			"\"&&\"",
			"\"||\"",
			"\"let\"",
			"<ID>",
			"<NUM>",
			"\"+\"",
			"\"-\"",
			"\"*\"",
			"\"/\"",
			"\"(\"",
			"\")\"",
			"\"=\"",
			"\";\"",
			"\";;\"",
			"\"{\"",
			"\"}\"",
	};
	
}
