/* Generated By:JavaCC: Do not edit this line. Parser0Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FN = 5;
  /** RegularExpression Id. */
  int DEREF = 6;
  /** RegularExpression Id. */
  int MUT = 7;
  /** RegularExpression Id. */
  int NEW = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int PRINTLN = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int GR = 17;
  /** RegularExpression Id. */
  int GREQ = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int LET = 21;
  /** RegularExpression Id. */
  int ID = 22;
  /** RegularExpression Id. */
  int NUM = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int LPAR = 28;
  /** RegularExpression Id. */
  int RPAR = 29;
  /** RegularExpression Id. */
  int BIND = 30;
  /** RegularExpression Id. */
  int SEMI = 31;
  /** RegularExpression Id. */
  int DSEMI = 32;
  /** RegularExpression Id. */
  int LCBRA = 33;
  /** RegularExpression Id. */
  int RCBRA = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int COLON = 36;
  /** RegularExpression Id. */
  int ARROW = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"fn\"",
    "\"~\"",
    "\"mut\"",
    "\"new\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"println\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"let\"",
    "<ID>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\";;\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":\"",
    "\"->\"",
  };

}
