/* Generated By:JavaCC: Do not edit this line. Parser0Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEREF = 5;
  /** RegularExpression Id. */
  int MUT = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int PRINTLN = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int EQ = 14;
  /** RegularExpression Id. */
  int GR = 15;
  /** RegularExpression Id. */
  int GREQ = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int LET = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int NUM = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int LPAR = 26;
  /** RegularExpression Id. */
  int RPAR = 27;
  /** RegularExpression Id. */
  int BIND = 28;
  /** RegularExpression Id. */
  int SEMI = 29;
  /** RegularExpression Id. */
  int DSEMI = 30;
  /** RegularExpression Id. */
  int LCBRA = 31;
  /** RegularExpression Id. */
  int RCBRA = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"~\"",
    "\"mut\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"println\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"let\"",
    "<ID>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\";;\"",
    "\"{\"",
    "\"}\"",
  };

}
